server:
  port: 8090
spring:
  application:
    name: "loans"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/
    username: root
    password: root
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
#    hibernate:
#      ddl-auto: update
  config:
    import: "optional:configserver:http://localhost:8071/"

#    docker run -it --rm --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3.12-management

management:
  endpoints:
    web:
      exposure:
        include: "*"